# docker-compose.yml
version: "3.7"
services:
  cron-runner:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ${IMAGE_REPOSITORY}:${IMAGE_TAG}
    container_name: cron-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # DooD
      - ./crontabs:/crontabs
      - .inenv:/.env
