# docker-compose.yml
version: "3.7"
services:
  cron-runner:
    build:
      context: ./
      dockerfile: Dockerfile
    image: ${IMAGE_REPOSITORY}:${IMAGE_TAG}
    container_name: cron-runner
    restart: always # docker起動時に毎回自動起動
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # ホストのdockerソケットをマウントすることでDooDを可能に
      - ./crontabs:/crontabs
